### ISSUE TITLE
running on padavan

### ISSUE THREAD

**Issue by swetoast** [spalife/ipBLOCKer#4]
/tmp/mnt/USBDRIVE1/ipBLOCKer

just change all paths to /opt/ipBLOCKer 

will make it run on both asuswrt and padavan :)

**Comment by spalife** [comment]
Good to hear from you, disappeared from the forum ?
Haven't been on padavan.

Testing it on ubuntu. System currently looks for the below in /opt/bin
bash diff grep sort split xargs

We can override that with adding the below in .ipBLOCKer.config for say ubuntu
PACKAGE_NAME="APT-GET"
PACKAGE_INSTALL_CMD="apg-get"
PACKAGE_INSTALL_OPTION="install"
PACKAGE_INSTALL_LOCATION="/usr/bin"

and link bash and grep to /usr/bin. You also will need to have the necessary privileges

**Comment by swetoast** [comment]
PACKAGE_NAME="OPKG"
PACKAGE_INSTALL_CMD="OPKG"
PACKAGE_INSTALL_OPTION="install"
PACKAGE_INSTALL_LOCATION="/opt/bin"

that would be valid for padavan

yeah i left the forum seen the drama on my threads and the haters not stopped with my script but ive seen that the scripters taken advantage of the situation and im not there to defend myself and my choices but malware filter and privacy continues. 

if  your planning multiple system support its a nice approach you got.

**Comment by spalife** [comment]
Appreciate your feedback and Information.
Such as life is ....
lot of folks would like to see you back on the forum.
Come back when you can.
